{
 "title": "Gatling",
 "time": { "from": "2020-09-24T17:15:46.302Z", "to": "2020-09-24T17:27:06.213Z" },
 "panels": [
  {
   "title": "Running Users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling.users",
     "query": "SELECT count(\"active\"), count(\"done\"), count(\"waiting\") FROM \"gatling.users\" WHERE (\"simulation\" = 'modifsimulation') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Active Users" ], "type": "alias" }
      ],
      [
       { "params": [ "done" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Done Users" ], "type": "alias" }
      ],
      [
       { "params": [ "waiting" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Waiting Users" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "simulation", "operator": "=", "value": "modifsimulation" }
     ]
    }
   ]
  },
  {
   "title": "Latencies: Percentiles & Max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "measurement": "gatling",
     "query": "SELECT \"percentiles50\" FROM \"gatling\" WHERE \"request\" = 'allRequests' AND \"status\" = 'ok' AND $timeFilter",
     "select": [
      [
       { "params": [ "percentiles50" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
     ]
    },
    {
     "measurement": "gatling",
     "query": "SELECT \"percentiles95\" FROM \"gatling\" WHERE \"request\" = 'allRequests' AND \"status\" = 'ok' AND $timeFilter",
     "select": [
      [
       { "params": [ "percentiles95" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
     ]
    },
    {
     "measurement": "gatling",
     "query": "SELECT \"percentiles99\" FROM \"gatling\" WHERE \"request\" = 'allRequests' AND \"status\" = 'ok' AND $timeFilter",
     "select": [
      [
       { "params": [ "percentiles99" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
     ]
    },
    {
     "measurement": "gatling",
     "query": "SELECT \"max\" FROM \"gatling\" WHERE \"request\" = 'allRequests' AND \"status\" = 'ok' AND $timeFilter",
     "select": [
      [
       { "params": [ "max" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Errors v Passes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Pass",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "measurement": "gatling",
     "query": "SELECT \"count\" FROM \"gatling\" WHERE (\"request\" = 'allRequests' AND \"status\" = 'ok') AND $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "Errors",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "measurement": "gatling",
     "query": "SELECT \"count\" FROM \"gatling\" WHERE \"request\" = 'allRequests' AND \"status\" = 'ko' AND $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ko" }
     ]
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "measurement": "gatling",
     "query": "SELECT \"count\" FROM \"gatling\" WHERE \"request\" = 'allRequests' AND \"status\" = 'all' AND $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Individual Requests (95% Line)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "request" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT \"percentiles95\" FROM \"gatling\" WHERE \"request\" <> 'allRequests' AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "percentiles95" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "<>", "value": "allRequests" }
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}