{
 "title": "k6 Load Testing Results By Groups",
 "description": "A dashboard for visualizing results from the k6.io load testing tool by groups, using the InfluxDB exporter.Based on https://grafana.com/dashboards/10660",
 "tags": [
  "k6",
  "load testing"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Measurement",
    "query": "http_req_duration,http_req_blocked,http_req_connecting,http_req_looking_up,http_req_receiving,http_req_sending,http_req_waiting"
   },
   {
    "name": "URL",
    "label": "URL",
    "query": "SHOW TAG VALUES WITH KEY = \"name\""
   },
   {
    "name": "Group",
    "label": "Group",
    "query": "SHOW TAG VALUES WITH KEY = \"group\" WHERE $timeFilter"
   },
   {
    "name": "Tag",
    "label": "Tag",
    "query": "SHOW TAG VALUES WITH KEY = \"name\" WHERE $timeFilter"
   }
  ]
 },
 "panels": [
  {
   "title": "Documentation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "content": "### To choose which measurements to show, use the **Measurements** drop-down in the top left corner!\n\nK6 collects metrics for several phases during the HTTP request lifetime.\n\nThe combined delays for the application and network (send, wait, recieve) are available in this metric:\n  * **http_req_duration**       _( Total time for request, excluding time spent blocked (http_req_blocked), DNS lookup (http_req_looking_up) and TCP connect (http_req_connecting) time. )_\n\nThis metric can also be broken down into these metrics:\n  * **http_req_tls_handshaking**     _( Time spent handshaking TLS session with remote host. )_\n  * **http_req_sending**      _( Time spent sending data to remote host.  )_\n  * **http_req_waiting**      _( Time spent waiting for response from remote host (a.k.a. \"time to first byte\", or \"TTFB\"). )_\n  * **http_req_receiving**       _( Time spent receiving response data from remote host. )_\n\nThese metrics measure delays and durations on the client:\n\n  * **http_req_blocked**     _( Time spent blocked (waiting for a free TCP connection slot) before initiating request.  )_\n  * **http_req_looking_up**     _( Time spent looking up remote host name in DNS. )_\n  * **http_req_connecting**     _( Time spent establishing TCP connection to remote host. )_\n\n\n### View official K6.io documentation here: [https://docs.k6.io/docs/result-metrics][1]\n\n\n[1]: https://docs.k6.io/docs/result-metrics\n\n"
    }
   ]
  },
  { "title": "K6 Test overview (all URLs)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Virtual Users",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Active VUs",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vus",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Requests per Second",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Tag$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Num Errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "errors",
     "query": "SELECT mean(\"value\") FROM \"errors\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$Group$/" }
     ]
    }
   ]
  },
  {
   "title": "Checks Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_check",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "check" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "checks",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$Group$/" }
     ]
    }
   ]
  },
  { "title": "$Measurement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "Measurement" },
  {
   "title": "$Measurement (over time per group)",
   "type": "graph",
   "description": "Grouped by 1 sec intervals and group name",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Tag$/" }
     ]
    }
   ]
  },
  {
   "title": "$Measurement (over time per tag)",
   "type": "graph",
   "description": "Grouped by 1 sec intervals and group name",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Tag$/" }
     ]
    }
   ]
  },
  {
   "title": "$Measurement (over time)",
   "type": "graph",
   "description": "Grouped by 1 sec intervals",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Tag$/" }
     ]
    },
    {
     "alias": "p95",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Tag$/" }
     ]
    },
    {
     "alias": "p90",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Tag$/" }
     ]
    },
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Tag$/" }
     ]
    }
   ]
  },
  {
   "title": "$Measurement (over time)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Tag$/" }
     ]
    }
   ]
  },
  {
   "title": "$Measurement (count)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 29 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Tag$/" }
     ]
    }
   ]
  },
  {
   "title": "$Measurement (min)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 29 },
   "format": "ms",
   "valueName": "min",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Tag$/" }
     ]
    }
   ]
  },
  {
   "title": "$Measurement (med)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 29 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Tag$/" }
     ]
    }
   ]
  },
  {
   "title": "$Measurement (max)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 29 },
   "format": "ms",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Tag$/" }
     ]
    }
   ]
  },
  {
   "title": "$Measurement (mean)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 29 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Tag$/" }
     ]
    }
   ]
  },
  {
   "title": "$Measurement (p95)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 29 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Tag$/" }
     ]
    }
   ]
  },
  {
   "title": "URLs and latencies (By Group)",
   "type": "table-old",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Tag$/" }
     ]
    }
   ]
  },
  {
   "title": "URLs and latencies (By Name)",
   "type": "table-old",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Tag$/" }
     ]
    }
   ]
  }
 ]
}